language: node_js
node_js:
  - "6"

# branches:
#   only:
#     - master

before_script:
  - npm install -g firebase-tools

script:
  - typings install
  - tsc -p .
  - npm test

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - firebase deploy --email ${FIREBASE_USERNAME} --password ${FIREBASE_PASSWORD}
